package com.tuxnet.project_euler;

// https://projecteuler.net/problem=2
/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */

public class Problem2 {
    /* TODO:
    1) ArrayList1 with Fibonacci numbers from range <1,4*10^6>
    2) ArrayList2 with even-valued numbers from ArrayList1
    3) Sum of numbers from ArrayList2
     */
}
